//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.detail = new HashSet<detail>();
            this.order = new HashSet<order>();
        }
    
        public int idCar { get; set; }
        public string vincod { get; set; }
        public string registrNumber { get; set; }
        public int ModelOfCar_idModelOfCar { get; set; }
        public int ColorOfCar_idColorOfCar { get; set; }
        public int Client_idClient { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual client client { get; set; }
        public virtual colorofcar colorofcar { get; set; }
        public virtual modelofcar modelofcar { get; set; }
        public virtual ICollection<detail> detail { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
