//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colorofcar
    {
        public colorofcar()
        {
            this.car = new HashSet<car>();
        }
    
        public int idColorOfCar { get; set; }
        public string nameColorOfCar { get; set; }
    
        public virtual ICollection<car> car { get; set; }
    }
}
