//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public detail()
        {
            this.process_has_detail = new HashSet<process_has_detail>();
        }
    
        public int idDetail { get; set; }
        public int StandartDetail_idStandartDetail { get; set; }
        public int Car_idCar { get; set; }
    
        public virtual car car { get; set; }
        public virtual standartdetail standartdetail { get; set; }
        public virtual ICollection<process_has_detail> process_has_detail { get; set; }
    }
}
