//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class markofcar
    {
        public markofcar()
        {
            this.modelofcar = new HashSet<modelofcar>();
        }
    
        public int idMarkOfCar { get; set; }
        public string nameMarkOfCar { get; set; }
    
        public virtual ICollection<modelofcar> modelofcar { get; set; }
    }
}
