//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelofcar
    {
        public modelofcar()
        {
            this.car = new HashSet<car>();
        }
    
        public int idModelOfCar { get; set; }
        public string nameModelOfCar { get; set; }
        public int MarkOfCar_idMarkOfCar { get; set; }
    
        public virtual ICollection<car> car { get; set; }
        public virtual markofcar markofcar { get; set; }
    }
}
