//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation
    {
        public operation()
        {
            this.process = new HashSet<process>();
            this.workerhasskill = new HashSet<workerhasskill>();
        }
    
        public int idOperation { get; set; }
        public string nameOperation { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<process> process { get; set; }
        public virtual ICollection<workerhasskill> workerhasskill { get; set; }
    }
}
