//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.photo = new HashSet<photo>();
            this.process = new HashSet<process>();
        }
    
        public int idOrder { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<bool> status { get; set; }
        public int Worker_idWorker { get; set; }
        public int Car_idCar { get; set; }
    
        public virtual car car { get; set; }
        public virtual worker worker { get; set; }
        public virtual ICollection<photo> photo { get; set; }
        public virtual ICollection<process> process { get; set; }
        public string Color { get; set; }
    }
}
