//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo
    {
        public int idPhoto { get; set; }
        public byte[] image { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public int Order_idOrder { get; set; }
    
        public virtual order order { get; set; }
    }
}
