//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_has_detail
    {
        public int idProcess_has_Detail { get; set; }
        public int Process_idProcess { get; set; }
        public int Detail_idDetail { get; set; }
    
        public virtual detail detail { get; set; }
        public virtual process process { get; set; }
    }
}
