//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class standartdetail
    {
        public standartdetail()
        {
            this.detail = new HashSet<detail>();
        }
    
        public int idStandartDetail { get; set; }
        public string nameStandartDetail { get; set; }
    
        public virtual ICollection<detail> detail { get; set; }
    }
}
