//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerhasskill
    {
        public int idWorkerHasSkill { get; set; }
        public Nullable<int> level { get; set; }
        public int Worker_idWorker { get; set; }
        public int Operation_idOperation { get; set; }
    
        public virtual operation operation { get; set; }
        public virtual worker worker { get; set; }
    }
}
