//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public worker()
        {
            this.order = new HashSet<order>();
            this.process = new HashSet<process>();
            this.workerhasskill = new HashSet<workerhasskill>();
        }
    
        public int idWorker { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
    
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<process> process { get; set; }
        public virtual ICollection<workerhasskill> workerhasskill { get; set; }
        public string getCode
        {
            get
            {
                return CoderDecoder.CoderDecoder.code(idWorker.ToString());
            }
        }
    }
}
